---
title: 三国演义                  # 标题
lang: zh-CN                     # 语言
toc: false                      # 是否生成目录
toc-title: 目录                 # 目录标题
toc-depth: 3                    # 目录深度
number-sections: true           # 是否为章节编号
bibliography: sci.bib         # 参考文献文件,放在与本文件同一目录下
csl: Nature.csl               # 引用样式文件,放在与本文件同一目录下(这里下载：https://www.zotero.org/styles/)
link-citations: true            # 引用启用超链接
link-bibliography: true         # 参考文献启用超链接

format:
  pdf:
    documentclass: book          # 文档类型
    pdf-engine: xelatex          # 使用xelatex引擎
    papersize: a5                # 纸张大小
    title-block-style: none      # 标题样式
    margin-top: 2.0cm            # 页边距上侧
    margin-bottom: 2.0cm         # 页边距下侧
    margin-left: 2.0cm           # 页边距左侧
    margin-right: 2.0cm          # 页边距右侧
    fig-cap-location: bottom     # 图例位置下侧
    fig-align: center            # 图居中对齐
    code-block-bg: "#f7f7f7"   #
    code-block-border-left: true #
    code-line-numbers: true      #
    keep-tex: false              # 是否保留中间tex文件
    include-in-header: _extensions/Victory-Hugo/cbook_1/preamble.tex
---

<!-- 前言部分不纳入目录，独立存在 -->

# 前言 {.unnumbered .unlisted}

《三国演义》，也称《三国志通俗演义》或《三国志演义》，是一部长篇历史小说，流传极广，影响很大，为人民所熟悉。

《三国演义》取材于东汉末年和魏、蜀、吴三国的历史，从东汉灵帝中平元年（公元184年）黄巾起义开始，一直叙写到晋武帝太康元年（公元280年）吴亡为止，差不多整整一个世纪。晋朝史学家陈寿把这段历史编成史书《三国志》，南朝宋人裴松之为《三国志》作注，博引群书，注文多出本文数倍，增补了许多材料。东晋习凿齿的《汉晋春秋》，也是一本写三国历史的史书。同时，有关三国的故事一直流传不断。南朝宋刘义庆的《世说新语》着重记载魏晋名公士族的言谈轶事。据杜宝《大业拾遗记》记载，隋炀帝时已有曹瞒谯水击蛟、刘备檀溪跃马等水上杂戏。唐朝李商隐的《骄儿诗》“或谑张飞胡，或笑邓艾吃”，可以看到，当时已用三国人物作为笑谑的材料。宋、元时代，三国人物已由民间艺人带上讲台或舞台，据宋孟元老《东京梦华录》记载，北宋“说三分”（即说三国故事）已是“说话”中的独立科目之一，并出现了专说“三分”的著名艺人。我们现在看到的三国故事的最早讲史话本，是元初至元三十一年（公元1294年）刊刻的《三分事略》，可能就是宋人说话的底本。《三分事略》共分上中下三卷，从刘秀赏春、司马仲相阴间断狱开篇；正文从桃园结义开始，以诸葛亮病死结束，长达八万多字，虽然叙写简率，但三国故事的始末已粗具梗概。金院本、元杂剧也常常搬演三国故事，现今存留的剧目就有四十多种，剧本有一二十种。元末明初的《三国演义》就是在上述史书、杂记和平话、戏曲的基础上写成的，写作者是罗贯中。“据正史，采小说，证文辞，通好尚”（高儒《百川书志》）的说法，是符合罗贯中写作《三国演义》的实际情况的。

现在可以见到的《三国演义》的最早本子，是明弘治甲寅（公元1494年）序、嘉靖壬午（公元1522年）刊刻的《三国志通俗演义》。全书二十四卷，分二百四十则，题“晋平阳侯陈寿史传，后学罗本贯中编次”。至于这个刻本与罗贯中原本之间，内容上有无不同，现在没有资料可供说明。在这以后，《三国演义》刊本越来越多，现在可见的明末刊本就有二十多种，说明流传很广。有的刊本除了加上总评、回评、眉批、夹批外，内容上几乎是相同的。

<!-- 目录 -->

\tableofcontents

<!-- 如下开始正文 -->

# 宴桃园豪杰三结义 斩黄巾英雄首立功

词曰： *滚滚长江东逝水，浪花淘尽英雄。是非成败转头空：青山依旧在，几度夕阳红。* *白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢：古今多少事，都付笑谈中。*

话说天下大势，分久必合，合久必分：周末七国分争，并入于秦；及秦灭之后，楚、汉分争，又并入于汉；汉朝自高祖斩白蛇而起义，一统天下，后来光武中兴，传至献帝，遂分为三国。推其致乱之由，殆始于桓、灵二帝。桓帝禁锢善类[^1]，崇信宦官。及桓帝崩，灵帝即位，大将军窦武、太傅陈蕃，共相辅佐；时有宦官曹节等弄权，窦武、陈蕃谋诛之，机事不密，反为所害，中涓[^2]自此愈横。

[^1]: 禁锢善类——指东汉桓帝刘志时的“党锢之祸”。其时宦官集团把持政权，引起士族官僚集团的反对，形成激烈的争斗。结果宦官集团得势，把士族集团中的大批反对派，镇压迫害，逮捕定罪。后虽释放，却终身不准做官，叫做“禁锢”。善类，意即好人，指反对宦官专权的士大夫。

[^2]: 中涓——皇帝宫廷中，管理通报、打扫清洁的臣子。此指宦官，也即太监。

# 张翼德怒鞭督邮 何国舅谋诛宦官

\underline{话说汉灵帝中平元年，天下大旱，民不聊生}。时有张翼德者，字益德，河东解良人也。少时好武艺，性豪爽仗义，常与乡里豪杰结为兄弟。及至长成，闻天下大乱，遂携家带口，往洛阳\textcolor[HTML]{AD9466}{投军}。

{{< include 其他章节内容.qmd >}}
